services:
  _defaults:
    public: false
    autowire: true

  Playbloom\Satisfy\Command\RebuildCommand:
    tags:
      - { name: console.command }

  Playbloom\Satisfy\Controller\ConfigurationController:
    public: true
    tags:
      - { name: container.service_subscriber }

  Playbloom\Satisfy\Controller\RepositoryController:
    public: true
    tags:
      - { name: container.service_subscriber }

  Playbloom\Satisfy\Controller\SatisController:
    public: true
    autoconfigure: true
    tags:
      - { name: container.service_subscriber }

  Playbloom\Satisfy\Controller\SecurityController:
    public: true
    tags:
      - { name: container.service_subscriber }

  Playbloom\Satisfy\Controller\WebhookController:
    public: true
    tags:
      - { name: container.service_subscriber }

  Playbloom\Satisfy\Service\Manager:
    public: true
    bind:
      Symfony\Component\Lock\LockInterface: '@lock.satis'

  Playbloom\Satisfy\Model\Configuration:
    lazy: true
    factory: ['@Playbloom\Satisfy\Service\Manager', 'getConfig']

  Playbloom\Satisfy\Persister\FilePersister:
    arguments:
      $filename: "%satis_filename%"
      $logPath: "%satis_log_path%"

  Playbloom\Satisfy\Persister\JsonPersister:
    class: Playbloom\Satisfy\Persister\JsonPersister
    public: false
    arguments:
      - '@Playbloom\Satisfy\Persister\FilePersister'
      - "@serializer"
      - 'Playbloom\Satisfy\Model\Configuration'

  Playbloom\Satisfy\Persister\ConfigurationNormalizer:
    tags:
      - { name: serializer.normalizer, priority: 1000 }

  Playbloom\Satisfy\Service\LockProcessor:
    public: true

  Playbloom\Satisfy\Process\ProcessFactory:
    arguments:
      $rootPath: "%kernel.project_dir%"
      $composerHome: "%composer.home%"

  Playbloom\Satisfy\Runner\SatisBuildRunner:
    public: true
    arguments:
      $satisFilename: "%satis_filename%"
    bind:
      Symfony\Component\Lock\LockInterface: "@lock.build"
    tags:
      - { name: kernel.event_listener, event: Playbloom\Satisfy\Event\BuildEvent, method: onBuild }

  ### Webhook handlers
  Playbloom\Satisfy\Webhook\BitbucketWebhook:
    public: true

  Playbloom\Satisfy\Webhook\GithubWebhook:
    public: true
    calls:
      - [setSecret, ["%github.secret%"]]
      - [setSourceUrls, ["%github.source_urls%"]]
      - [setAutoAdd, ["%github.auto_add_repo%"]]
      - [setAutoAddType, ["%github.auto_add_repo_type%"]]

  Playbloom\Satisfy\Webhook\GiteaWebhook:
    public: true
    calls:
      - [setSecret, ["%gitea.secret%"]]
      - [setSourceUrls, ["%gitea.source_urls%"]]
      - [setAutoAdd, ["%gitea.auto_add_repo%"]]
      - [setAutoAddType, ["%gitea.auto_add_repo_type%"]]

  Playbloom\Satisfy\Webhook\GitlabWebhook:
    public: true
    arguments:
      $secret: "%gitlab.secret%"
      $autoAdd: "%gitlab.auto_add_repo%"
      $autoAddType: "%gitlab.auto_add_repo_type%"
      $preferSshUrlType: "%gitlab.prefer_ssh_url_type%"

  Playbloom\Satisfy\Validator\EnvValidator:
    public: true
    arguments:
      $root: "%kernel.project_dir%"
      $satisFilename: "%satis_filename%"
      $composerHome: "%composer.home%"

  Playbloom\Satisfy\Webhook\DevOpsWebhook:
    autowire: true
    public: true
    arguments:
      $secret: "%devops.secret%"
